name: Hello

on:
  pull_request:
    branches:
      - main
    paths:
      - "*.sh"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install needed packages
        run: |
          sudo apt update && sudo apt install python3 && sudo apt -y install python3-yaml

      - name: run cmd
        run: |
          cat helo.sh

          
